### PR TITLE
Hardware: list devices with or without issue

### PR DESCRIPTION
**Pull request by mlep**
Based on XCSoar/XCSoar#1279, give a better help to users for choosing a device by listing devices known to work well, or to have issues.

### CODE REVIEW

**Comment by lordfolken** [comment]
Have a look at the codacy suggestions, edit and force push.

**Comment by mlep** [comment]
I think I have solved the warning.
I guess the warnings also meant the initial file did not follow the prescribed syntax.

**Comment by lordfolken** [comment]
Well i wanted a force push so there is only one commit. 
Git rebase -i HEAD~3

Merge and fixup the commits, then force push.

**Review by lordfolken — APPROVED** [review]

**Comment by mlep** [comment]
> Well i wanted a force push so there is only one commit. Git rebase -i HEAD~3
> 
> Merge and fixup the commits, then force push.
Sorry for the inconvenience, but I did not find how to do it in the github webpage...

**Comment by lordfolken** [comment]
yeah.. that's my personal fear. That people are no longer able to use a computer and depend on a proprietary interface. Sad that we have reached that stage.

**Pull request merged**
